version:  'continuous.{build}'

branches:
  only:
    - master
    - develop
  except:
    - # Do not build tags that we create when we or travis upload to GitHub Releases
    - # does not work see https://github.com/appveyor/ci/issues/1493
    - /^(?i:continuous)$/
    - /continuous/

# # Do not build on tags (GitHub and BitBucket)
# skip_tags: true

# # Start builds on tags only (GitHub and BitBucket)
# skip_non_tags: true

# Including commits with particular message or from specific user
only_commits:
  #message: /build/                # Start a new build if message contains 'build'
  author: dimitris.kalamaras@gmail.com      # Start a new build for commit of user with email jack@company.com

# clone directory
clone_folder: c:\projects\socnetv

install:
  - cmd: echo %APPVEYOR_REPO_COMMIT%
  - cmd: echo %APPVEYOR_REPO_TAG%

  - cmd: echo "Setting last commit short id"
  - cmd: git rev-parse --short HEAD > MYVER.txt
  - cmd: set /p LAST_COMMIT_SHORT= < MYVER.txt
  - cmd: echo %LAST_COMMIT_SHORT%
  - cmd: del MYVER.txt
  - echo %APPVEYOR_REPO_COMMIT:~0,7%
  - cmd: echo "Setting SocNetV current version"
  - cmd: set SOCNETV_VERSION=2.6-dev
  - cmd: echo %SOCNETV_VERSION%

  - cmd: echo "Setting BUILDNAME" 
  - if "%APPVEYOR_REPO_TAG%"=="true" set BUILDNAME=%APPVEYOR_REPO_TAG_NAME%-%LAST_COMMIT_SHORT%  
  - if "%APPVEYOR_REPO_TAG%"=="true" if "%APPVEYOR_REPO_TAG_NAME%"=="continuous" set BUILDNAME=%SOCNETV_VERSION%-%LAST_COMMIT_SHORT% 
  - if "%APPVEYOR_REPO_TAG%"=="false" set BUILDNAME=%SOCNETV_VERSION%-%LAST_COMMIT_SHORT%
  - cmd: echo %BUILDNAME%

  - cmd: echo "Setting Qt environment..."
  - set QTDIR=C:\Qt\5.12.1\mingw73_64
#  - cmd: echo "Check Qt folders..."      
  - cmd: dir C:\Qt\Tools
#  - cmd: dir C:\Qt\Tools\mingw730_64\bin
#  - cmd: dir C:\Qt\5.12.1\mingw73_64
#  - cmd: dir C:\Qt\5.12.1\mingw73_64\bin
#  - cmd: dir C:\Qt\5.12.1\mingw73_64\plugins  
  - cmd: echo "Check project folder..."        
  - cmd: dir C:\projects\socnetv  
  - cmd: echo "Installing Innosetup..."  
  - choco install -y InnoSetup
  - cmd: echo "Setting paths..."    
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw730_64\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"

build_script:
  - cmd: echo "Running qmake..."  
  - qmake "CONFIG+=release" socnetv.pro
  - cmd: echo "BUILDING starts here with mingw32..."    
  - mingw32-make

after_build:
  - cmd: echo "check folder contents"
  - cmd: dir C:\projects\socnetv
  - cmd: dir C:\projects\socnetv\release  

  - cmd: echo "Executing windeployqt"
  - windeployqt release/socnetv.exe

  - cmd: echo "check folder contents again..."
  - cmd: dir C:\projects\socnetv\release  

  - cmd: echo "Deleting *.o and *.cpp..."  
  - cmd: del C:\projects\socnetv\release\*.cpp
  - cmd: del C:\projects\socnetv\release\*.o

  - cmd: echo "check folder contents again..."
  - cmd: dir C:\projects\socnetv\release  

  - cmd: cp COPYING release/LICENSE.txt"

  - cmd: echo "Running Innosetup..."
  - iscc innosetup.iss
  - cmd: type Setup-Manifest.txt

  - cmd: dir SocNetV*.exe

  - cmd: echo "Renaming file"
  - cmd: rename SocNetV-*installer.exe SocNetV-%BUILDNAME%-windows-installer.exe
  - cmd: dir SocNetV*.exe  
  - cmd: dir

artifacts:
  - path: SocNetV-*-installer.exe


# Deploy to GitHub Releases
deploy: 
  - provider: GitHub
    tag: continuous
    description: 'Continuous Integration release'
    artifact: /SocNetV.*installer\.exe/
    auth_token:
      secure: owdxko+lS3nNcxIsxL4OTdfZ5UPwudTp2vtk8TlErxd0/tqAfsPGmZ8BjN5sYTTk # your encrypted token from GitHub    
    draft: true
    prerelease: false
  # on:
  #   branch: master                # release from master branch only
  #   APPVEYOR_REPO_TAG: false      # deploy on tag push only


# Notify developer on any change
notifications:
  # Email
  - provider: Email
    to:
      - dimitris.kalamaras@gmail.com
    subject: '[socnetv/app] build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_status_changed: true
